# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170418_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
